title: Narasinga Lokesh Cherukuri
logo: /assets/img/pro-pic-logo.png
description: I’m a results-driven software engineer with hands-on experience in cloud engineering, DevOps, and full-stack development. I specialize in building robust, high-performing systems, automating workflows with tools like Terraform and Ansible, and optimizing CI/CD pipelines. Known for tackling challenges with a focus on scalability and efficiency, I’m ready to bring my skills to diverse projects and explore new technologies that push boundaries.
#show_downloads: true
theme: jekyll-theme-minimal
